name: "CI"
on:
  push:
    branches:
  pull_request:

jobs:
  "node-test":
    name: "Build and test on Node.js"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout this repo"
      uses: actions/checkout@v3
    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
        cache: "npm"
    - name: "Install npm dependencies"
      run: "npm ci"

    - name: "Checkout hrana-test-server"
      uses: actions/checkout@v3
      with:
        repository: "libsql/hrana-test-server"
        path: "hrana-test-server"
    - name: "Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: "Install pip dependencies"
      run: "pip install -r hrana-test-server/requirements.txt"

    - name: "Build"
      run: "npm run build"
    - name: "Test version 1 over WebSocket"
      run: "python hrana-test-server/server_v1.py npm test"
      env: {"VERSION": "1", "URL": "ws://localhost:8080"}
    - name: "Test version 2 over WebSocket"
      run: "python hrana-test-server/server_v2.py npm test"
      env: {"VERSION": "2", "URL": "ws://localhost:8080"}
    - name: "Test version 2 over HTTP"
      run: "python hrana-test-server/server_v2.py npm test"
      env: {"VERSION": "2", "URL": "http://localhost:8080"}
    - name: "Test version 3 over WebSocket and JSON"
      run: "python hrana-test-server/server_v3.py npm test"
      env: {"VERSION": "3", "URL": "ws://localhost:8080", "ENCODING": "json"}
    - name: "Test version 3 over WebSocket and Protobuf"
      run: "python hrana-test-server/server_v3.py npm test"
      env: {"VERSION": "3", "URL": "ws://localhost:8080", "ENCODING": "protobuf"}
    - name: "Test version 3 over HTTP and JSON"
      run: "python hrana-test-server/server_v3.py npm test"
      env: {"VERSION": "3", "URL": "http://localhost:8080", "ENCODING": "json"}
    - name: "Test version 3 over HTTP and Protobuf"
      run: "python hrana-test-server/server_v3.py npm test"
      env: {"VERSION": "3", "URL": "http://localhost:8080", "ENCODING": "protobuf"}
    - name: "Example"
      run: "python hrana-test-server/server_v3.py node examples/readme_example.js"
